// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"time"
)

type Message struct {
	ID        int64
	Text      string
	CreatedAt time.Time
	UpdatedAt time.Time
}
