// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Feature struct {
	Name string
	Seq  int64
}

type Message struct {
	ID        int64
	Text      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type MessagesFeature struct {
	MessageID   int64
	FeatureName string
	Count       int64
}

type Notification struct {
	ID        int64
	MessageID int64
	Type      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type RecurringNotification struct {
	NotificationID int64
	TriggerAtTime  sql.NullString
}

type RecurringNotificationDay struct {
	RecurringNotificationID int64
	WeekDay                 string
}

type SimpleNotification struct {
	NotificationID int64
	TriggerAt      time.Time
}

type TypeEnum struct {
	Type string
	Seq  sql.NullInt64
}

type WeekDayEnum struct {
	WeekDay string
	Seq     sql.NullInt64
}
