CREATE TABLE notifications (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    message_id INTEGER NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    type TEXT NOT NULL REFERENCES type_enum(type) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE type_enum (
    type TEXT PRIMARY KEY NOT NULL,
    seq INTEGER
);

INSERT INTO features (name, seq) VALUES ('notifications', 1);
